local Clock = module("clock")
local test, equal = harness.test, harness.equal

test("the clamp never goes below the last host seconds", function()
  equal(Clock.clamp(100, 50), 100)
  equal(Clock.clamp(40, 50), 50)
  equal(Clock.clamp(50, 50), 50)
end)

test("a clock set back is read as the last time seen", function()
  local clock = Clock.new(1000)
  equal(clock:read(900), 1000, "before the save's last seconds")
  equal(clock:read(1200), 1200)
  equal(clock:read(1100), 1200, "after going back")
end)

test("no tick is due until the reader is open", function()
  local clock = Clock.new(0)
  equal(clock:tickDue(1000), false, "on the shelf")
  clock:start(1000)
  equal(clock:tickDue(1000 + Clock.TICK_SECONDS - 1), false, "too soon")
  equal(clock:tickDue(1000 + Clock.TICK_SECONDS), true, "on time")
  equal(clock:tickDue(1000 + Clock.TICK_SECONDS + 1), false, "the count restarts")
end)

test("time away owes no tick", function()
  local clock = Clock.new(0)
  clock:start(100)
  clock:stop()
  equal(clock:tickDue(100 + 1000), false, "stopped")
  clock:start(100 + 1000)
  equal(clock:tickDue(100 + 1000 + 1), false, "the count began again at the start")
end)

test("a clock that went back owes nothing and is never negative", function()
  local clock = Clock.new(0)
  clock:start(500)
  equal(clock:tickDue(100), false, "set back")
  equal(clock.last, 500)
  equal(clock:tickDue(500 + Clock.TICK_SECONDS), true, "the first tick after")
end)
