/*
 * The Unicode rules the runtime takes from the JavaScript runtime, as tables generated by
 * scripts/generate-prose-unicode.mjs: for prose's capitalising (the spec's Prose > Slots), which
 * code points are letters or numbers and what a code point of the Basic Multilingual Plane becomes
 * in upper case, special casing included; and for nicknames (the spec's Names > Nicknames), what a
 * code point becomes in lower case, the classes lower-casing a final sigma reads, and which code
 * points are control or format characters.
 */
#ifndef SPROUT_PROSE_UNICODE_H
#define SPROUT_PROSE_UNICODE_H

#include <stdbool.h>
#include <stddef.h>

/* Whether the code point is a letter or a number (general categories L and N). */
bool prose_unicode_letter_or_number(unsigned long cp);

/*
 * Writes the upper case of `cp` to `out` and returns how many code points that is, from one to
 * three. A code point past the Basic Multilingual Plane is its own upper case, as it is to
 * JavaScript's `toUpperCase` of the single UTF-16 code unit `capitalise` reads.
 */
size_t prose_unicode_upper(unsigned long cp, unsigned long out[3]);

/* Writes the lower case of `cp` to `out` and returns how many code points that is, one or two. */
size_t prose_unicode_lower(unsigned long cp, unsigned long out[2]);

/* Whether the code point is cased (`\p{Cased}`) or case-ignorable (`\p{Case_Ignorable}`). */
bool prose_unicode_cased(unsigned long cp);
bool prose_unicode_case_ignorable(unsigned long cp);

/* Whether the code point is a control or format character (general categories Cc and Cf). */
bool prose_unicode_control_or_format(unsigned long cp);

#endif
