/*
 * The two Unicode rules prose's capitalising takes from the JavaScript runtime (the spec's
 * Prose > Slots), as tables generated by scripts/generate-prose-unicode.mjs: which code
 * points are letters or numbers, and what a code point of the Basic Multilingual Plane
 * becomes in upper case, special casing included.
 */
#ifndef SPROUT_PROSE_UNICODE_H
#define SPROUT_PROSE_UNICODE_H

#include <stdbool.h>
#include <stddef.h>

/* Whether the code point is a letter or a number (general categories L and N). */
bool prose_unicode_letter_or_number(unsigned long cp);

/*
 * Writes the upper case of `cp` to `out` and returns how many code points that is, from one to
 * three. A code point past the Basic Multilingual Plane is its own upper case, as it is to
 * JavaScript's `toUpperCase` of the single UTF-16 code unit `capitalise` reads.
 */
size_t prose_unicode_upper(unsigned long cp, unsigned long out[3]);

#endif
