// The generated skill: the builder's reference, generated from the
// compiler's own tables (the spec's The compiler › The generated skill).
// It is ordered for an author, as the spec asks — the worked example
// first, composition and routing last — and every section is read from
// what this compiler implements: its parser's words, its checker's, its
// limits, its warnings and refusals in its own words, the standard
// library it carries, and the extensions a host installs. It is Markdown
// with a skill's front matter, so a model can be handed it as it is.

import { compileSnippet } from './bench.js';
import { workedExampleSection } from './example.js';
import {
  compositionSection,
  librarySourceSection,
  routingSection,
  verbsSection,
} from './library.js';
import { blocks, code, fenced, heading } from './markdown.js';
import { refusalsSection, warningsSection } from './problems.js';
import {
  declarationsSection,
  extensionsSection,
  limitsSection,
  manifestSection,
  reservedSection,
} from './reference.js';
import { statementsSection } from './statements.js';
import { valuesSection } from './values.js';
import { LANGUAGE_LEVEL, libraryHash } from '../bundle.js';
import { DEFAULT_LIMITS, type Limits } from '../limits.js';
import { STANDARD_LIBRARY } from '../standard-library.js';
import type { Extension } from '../../declare/extensions.js';

/** What a host brings to the skill it generates. */
export interface SkillOptions {
  /** The host's limits, whose figures the skill gives; the spec's defaults unless it says otherwise. */
  readonly limits?: Limits;
  /** The extensions the host installs, each described with its own paragraph; none unless it says so. */
  readonly extensions?: readonly Extension[];
  /** How a tool that carries the skill checks a world, shown as it is: a command line's usage. */
  readonly usage?: string;
}

/** The skill's front matter and opening, which say what it is and what it was generated from. */
function opening(): string {
  const library = `${STANDARD_LIBRARY.name} ${STANDARD_LIBRARY.version}`;
  return blocks(
    [
      '---',
      'name: sprout',
      'description: Write and fix Sprout microworlds — small multiplayer interactive-fiction worlds of ' +
        'places, things and the kinds they are made of. Use when writing .sprout or .prose files, a ' +
        'sprout.json manifest, or reading what the Sprout compiler said about them.',
      '---',
    ].join('\n'),
    heading(1, 'Writing a Sprout world'),
    `Generated by the Sprout compiler at language level ${LANGUAGE_LEVEL}, from its own tables, with ` +
      `the standard library ${code(library)} (${code(libraryHash(STANDARD_LIBRARY).slice(0, 12))}). ` +
      'Every example here was compiled when this was generated, and every message is the compiler’s own; ' +
      'where this page and the compiler disagree, the compiler is right and this page is out of date.',
  );
}

/** How to check what was written, where the tool carrying the skill says. */
function checkingSection(usage: string): string {
  return blocks(heading(2, 'Checking what you wrote'), fenced('text', usage));
}

/** The whole skill, as one Markdown page, in the order an author reads it. */
export function generateSkill(options: SkillOptions = {}): string {
  const { bundle } = compileSnippet({});
  if (bundle === null) throw new Error('The standard library does not compile on its own.');
  const page = blocks(
    opening(),
    workedExampleSection(),
    options.usage === undefined ? '' : checkingSection(options.usage),
    manifestSection(),
    declarationsSection(),
    valuesSection(),
    statementsSection(),
    verbsSection(bundle),
    warningsSection(),
    refusalsSection(),
    limitsSection(options.limits ?? DEFAULT_LIMITS),
    reservedSection(),
    extensionsSection(options.extensions ?? []),
    compositionSection(bundle),
    routingSection(bundle),
    librarySourceSection(),
  );
  return `${page}\n`;
}
